# Generated by Django 4.2.16 on 2024-11-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='format',
            new_name='content_category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='section',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='source_data',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='subsection',
            new_name='structure',
        ),
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.AddField(
            model_name='article',
            name='fact_check_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='style',
            field=models.CharField(default='기본 스타일', max_length=100),
        ),
    ]
