# Generated by Django 4.2.16 on 2024-11-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0005_article_created_at_article_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='design',
            new_name='literary',
        ),
    ]
