# Generated by Django 5.0.6 on 2024-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articletable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True, db_column="Title", null=True)),
                ("link", models.TextField(blank=True, db_column="Link", null=True)),
                (
                    "content",
                    models.TextField(blank=True, db_column="Content", null=True),
                ),
                ("format", models.TextField(blank=True, db_column="Format", null=True)),
                (
                    "keywords",
                    models.TextField(blank=True, db_column="Keywords", null=True),
                ),
                (
                    "section",
                    models.TextField(blank=True, db_column="Section", null=True),
                ),
                (
                    "subsection",
                    models.TextField(blank=True, db_column="SubSection", null=True),
                ),
            ],
            options={
                "db_table": "articletable",
                "managed": True,
            },
        ),
    ]
