# Generated by Django 5.0.6 on 2024-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articlesimilarity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlesimilarityArticle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "articlesimilarity_article",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Articletable",
        ),
    ]
