# Generated by Django 5.0.6 on 2024-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articlesimilarity", "0002_articlesimilarityarticle_delete_articletable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articletable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, db_column="Title", null=True)),
                (
                    "content",
                    models.TextField(blank=True, db_column="Content", null=True),
                ),
                ("format", models.TextField(blank=True, db_column="Format", null=True)),
                (
                    "keywords",
                    models.TextField(blank=True, db_column="Keywords", null=True),
                ),
                (
                    "section",
                    models.TextField(blank=True, db_column="Section", null=True),
                ),
                (
                    "subsection",
                    models.TextField(blank=True, db_column="SubSection", null=True),
                ),
            ],
            options={
                "db_table": "articletable",
                "managed": False,
            },
        ),
    ]
