# Generated by Django 5.0.6 on 2024-07-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articlesimilarity", "0003_articletable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextprocessorArticle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("keywords", models.JSONField()),
                ("format", models.CharField(max_length=100)),
                ("section", models.CharField(max_length=100)),
                ("subsection", models.CharField(max_length=100)),
            ],
        ),
    ]
