# Generated by Django 5.0.6 on 2024-07-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articlesimilarity", "0004_textprocessorarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utf8Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(blank=True, db_column="Title", null=True)),
                ("link", models.TextField(blank=True, db_column="Link", null=True)),
                (
                    "content",
                    models.TextField(blank=True, db_column="Content", null=True),
                ),
                ("format", models.TextField(blank=True, db_column="Format", null=True)),
                (
                    "keywords",
                    models.TextField(blank=True, db_column="Keywords", null=True),
                ),
                (
                    "section",
                    models.TextField(blank=True, db_column="Section", null=True),
                ),
                (
                    "subsection",
                    models.TextField(blank=True, db_column="SubSection", null=True),
                ),
            ],
            options={
                "db_table": "utf8article",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="TextprocessorArticle",
        ),
        migrations.DeleteModel(
            name="ArticlesimilarityArticle",
        ),
        migrations.DeleteModel(
            name="Articletable",
        ),
    ]
