# Generated by Django 4.2.16 on 2024-10-31 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_word', models.CharField(max_length=100, verbose_name='Target Word')),
                ('part_of_speech', models.CharField(max_length=50, verbose_name='Part of Speech')),
                ('correct_form', models.TextField(verbose_name='Correct Form')),
            ],
            options={
                'verbose_name': 'Vocabulary Rule',
                'verbose_name_plural': 'Vocabulary Rules',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.article'),
        ),
    ]
