# Generated by Django 4.2.16 on 2024-11-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_vocabularyrule_correct_form_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vocabularyrule',
            name='unique_target_word_pos',
        ),
        migrations.AddField(
            model_name='vocabularyrule',
            name='has_final_consonant',
            field=models.BooleanField(blank=True, help_text='Indicates whether the target word has a final consonant.', null=True, verbose_name='Has Final Consonant'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyrule',
            constraint=models.UniqueConstraint(fields=('target_word', 'pos', 'has_final_consonant'), name='unique_target_word_pos_consonant'),
        ),
    ]
