# Generated by Django 4.2.16 on 2024-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_vocabularyrule_unique_target_word_pos_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vocabularyrule',
            name='unique_target_word_pos_consonant',
        ),
        migrations.RemoveField(
            model_name='vocabularyrule',
            name='has_final_consonant',
        ),
        migrations.AddConstraint(
            model_name='vocabularyrule',
            constraint=models.UniqueConstraint(fields=('target_word', 'pos'), name='unique_target_word_pos'),
        ),
    ]
